version: '3'

services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: courseDB
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
